name: Acceso a la fortaleza prohibida

on: 
  workflow_dispatch:

jobs:
  acceso-a-la-base:
    runs-on: ubuntu-latest

    steps:
      - name: El agente llega a la fortaleza
        run: |
          echo "Agente ${{ github.actor }} ha llegado a la fortaleza prohibida"
          echo "  "
          echo "Buscar os archivos de la legion"
          ls -la
          echo ""
          echo "pero que paso? no hay nada"
      
      - name : "Brainiac desbloquea la boveda"
        uses : actions/checkout@v4

      - name: "Ahora si vamos a ver los planes"
        run: |
          echo "Ahora si vamos a ver los planes"
          ls -la
          echo " Funciona"

          echo "planes"
          ls planes/
          echo "Villanos:"
          ls miembros/
          echo "Inteligencia"
          ls inteligencia/
          