
name: Comunicador de la leigion

# Controls when the workflow will run
on:
  
  workflow_dispatch:
    inputs:
       villano:
          description: " Que villano envia el mensaje?"
          required: true
          type: choice
          options:
            - Lex Luthor
            - Joker
            - Darkseid
            - Sinestro


       prioridad:
          description: " Nivel de prioridad"
          required: true
          type: choice
          options:
            - Normal
            - Alta
            - Critica

       mensaje:
          description: "Mensaje para el consejo"
          required: true
          default: "La mision fue un exito"
          

     
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Transmitir-mensaje:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Imprimir inputs
        run: |
          echo "Inputs:"
          echo ""
          echo "Villano: ${{ inputs.villano }}"
          echo "Nivel: ${{ inputs.prioridad }}"
          echo "Mensaje: ${{ inputs.mensaje }}"
